# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic', models.ImageField(blank=True, upload_to='user_imgs')),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
        migrations.AddField(
            model_name='manager',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offside.Team'),
        ),
    ]
