# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offside', '0002_auto_20171204_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic', models.ImageField(blank=True, upload_to='static/img/staff/player')),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offside.Team')),
            ],
        ),
        migrations.AlterField(
            model_name='manager',
            name='pic',
            field=models.ImageField(blank=True, upload_to='static/img/staff/manager'),
        ),
    ]
