# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offside', '0005_auto_20171204_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='nth',
            field=models.IntegerField(default=1),
        ),
    ]
