# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offside', '0007_match_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='Defender', max_length=30),
        ),
    ]
