# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offside', '0008_auto_20171205_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(default='Fatih Terim', on_delete=django.db.models.deletion.CASCADE, to='offside.Team'),
        ),
    ]
