# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offside', '0009_auto_20171206_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='stadium',
        ),
        migrations.AlterField(
            model_name='match',
            name='stadium',
            field=models.CharField(max_length=50),
        ),
    ]
