# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offside', '0010_auto_20171206_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, default='1-1', max_length=10),
        ),
    ]
