# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offside', '0012_auto_20171212_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='League',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offside.League'),
            preserve_default=False,
        ),
    ]
