# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offside', '0013_manager_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('desc', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('League', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offside.League')),
            ],
        ),
    ]
