# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offside', '0014_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
