# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offside', '0015_auto_20171214_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=10)),
                ('colour', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('pic', models.ImageField(blank=True, upload_to='static/img/product')),
            ],
        ),
    ]
