# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offside', '0016_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offside.Team'),
            preserve_default=False,
        ),
    ]
