# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offside', '0020_comment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
    ]
