# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offside', '0021_auto_20171224_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pic',
            field=models.ImageField(blank=True, upload_to='static/img/news'),
        ),
    ]
