# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offside', '0031_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offside.News')),
            ],
        ),
    ]
