# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 22:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offside', '0032_commentnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentnews',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
